spring:
  cloud:
    gateway:
      routes:
        - predicates:
          - Path=/gateway/**
          filters:
            - StripPrefix=1
          uri: http://localhost:8082/
server:
  port: 8083