spring:
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
      refresh:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3308/goodsdb?serverTimezone=UTC&useSSL=true
    username: root
    password: Everyday@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: 192.168.182.130:9092
    consumer:
      group-id: order-server
  application:
    name: order-service

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
server:
  port: 8082
mybatis:
  type-aliases-package: com.springcloud.learn.example.orderserviceprovider.mapper.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com.springcloud.learn.goods.goodsserviceprovider.mapper: debug