spring:
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
      refresh:
        enabled: true
  kafka:
    bootstrap-servers: 192.168.182.130:9092
    consumer:
      group-id: user-server
  application:
    name: user-service

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
server:
  port: 8081